# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="terminaltables"
REALVERSION="2.1.0"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,3_3,3_4,3_5} )

inherit gs-pypi

DESCRIPTION="Generate simple tables in terminals from a nested list of strings."

HOMEPAGE="https://github.com/Robpol86/terminaltables"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

