# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="Flask-Login"
REALVERSION="0.4.0"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,3_3,3_4,3_5,3_3,3_4} )

inherit gs-pypi

DESCRIPTION="User session management for Flask"

HOMEPAGE="https://github.com/maxcountryman/flask-login"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"
