# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="Flask-Cors"
REALVERSION="2.1.2"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,3_3,3_4,3_5,3_3,3_3} )

inherit gs-pypi

DESCRIPTION="A Flask extension adding a decorator for CORS support"

HOMEPAGE="https://github.com/corydolphin/flask-cors"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

