# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="pytvmaze"
REALVERSION="2.0.8"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,3_5} )

inherit gs-pypi

DESCRIPTION="Python interface to the TV Maze API (www.tvmaze.com)"

HOMEPAGE="https://github.com/srob650/pytvmaze"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

