# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="Flask-Compress"
REALVERSION="1.3.0"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,2_7,3_3,3_4,3_5,3_3,3_4} )

inherit gs-pypi

DESCRIPTION="Compress responses in your Flask app with gzip."

HOMEPAGE="https://github.com/wichitacode/flask-compress"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

