# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$
# Ebuild generated by g-pypi 0.4

EAPI="6"
PYTHON_COMPAT=( python2_7 )

inherit distutils-r1

MY_PN="Flask-Compress"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Compress responses in your Flask app with gzip."
HOMEPAGE="https://github.com/wichitacode/flask-compress"
SRC_URI="mirror://pypi/${P:0:1}/${PN}/${MY_P}.tar.gz -> ${P}.tar.gz"

LICENSE="MIT"
KEYWORDS="~amd64" "~x86"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="dev-python/flask
	dev-python/setuptools"

S="${WORKDIR}/${MY_P}"
