# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="flask-restplus"
REALVERSION="0.8.6"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,2_7,3_3,3_4,3_5,3_3,3_4,3_5} )

inherit gs-pypi distutils-r1

DESCRIPTION="Helpers, syntaxic sugar and Swagger documentation for Flask-Restful"

HOMEPAGE="https://github.com/noirbizarre/flask-restplus"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

python_prepare_all() {
	# Disable benchmarks as they require unavailable pytest-benchmark.
	#rm guessit/test/test_benchmark.py || die
	#sed -i -e "s|'pytest-benchmark',||g" setup.py || die

	# Disable unconditional dependency on dev-python/pytest-runner.
	#sed -i -e "s|'pytest-runner'||g" setup.py || die

	distutils-r1_python_prepare_all
}
PATCHES=( "${FILESDIR}"/distutils_r1-tests-packaging-fix.patch )
