# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="zxcvbn-python"
REALVERSION="4.4.14"
# no baja
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} )

inherit gs-pypi

DESCRIPTION="Python implementation of Dropbox's realistic password strength estimator, zxcvbn"

HOMEPAGE="https://github.com/srob650/pytvmaze"
LICENSE=""

SLOT="0"
KEYWORDS="~amd64 ~x86"
