# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="colorclass"
REALVERSION="2.2.0"
#no baja
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} )

inherit gs-pypi

DESCRIPTION="Colorful worry-free console applications for Linux, Mac OS X, and Windows."

HOMEPAGE="https://github.com/Robpol86/colorclass"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"
